//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public CustomerData()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Petname { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
