//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string petname { get; set; }
        public string specie { get; set; }
        public string sex { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual user user { get; set; }
    }
}
