//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.pets = new HashSet<pet>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<pet> pets { get; set; }
    }
}
